# Generated by Django 4.1.2 on 2022-10-07 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0002_alter_thing_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Thing',
            new_name='Things',
        ),
    ]
