# Generated by Django 4.1.2 on 2022-10-07 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0003_rename_thing_things'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Things',
            new_name='Thing',
        ),
    ]
